
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "MultiNetwork_common.h"
namespace MultiC2S
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_RequestServerIn,
               
		Rmi_RequestLogin,
               
		Rmi_RequestRoomList,
               
		Rmi_RequestInRoom,
               
		Rmi_RequestFastRoom,
               
		Rmi_RequestInGame,
               
		Rmi_JoinGameScene,
               
		Rmi_Player_SMove,
               
		Rmi_RequestAddTree,
               
		Rmi_RequestRemoveTree,
	};

	int g_RmiIDListCount = 10;
}
namespace MultiS2C
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ReplyServerIn,
               
		Rmi_ReplyServerFailed,
               
		Rmi_NotifyLoginSuccess,
               
		Rmi_NotifyLoginFailed,
               
		Rmi_ReplyInRoom,
               
		Rmi_ReplyInGame,
               
		Rmi_NotifyAddTree,
               
		Rmi_NotifyRemoveTree,
               
		Rmi_Player_Appear,
               
		Rmi_Player_Disappear,
	};

	int g_RmiIDListCount = 10;
}
namespace MultiC2C
{
	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ScribblePoint,
               
		Rmi_OtherCharacterSelect,
               
		Rmi_Player_CMove,
	};

	int g_RmiIDListCount = 3;
}
