 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace MultiC2S
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestServerIn = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID RequestLogin = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID RequestRoomList = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID RequestInRoom = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID RequestFastRoom = (Nettention.Proud.RmiID)3000+5;
			public const Nettention.Proud.RmiID RequestInGame = (Nettention.Proud.RmiID)3000+6;
			public const Nettention.Proud.RmiID JoinGameScene = (Nettention.Proud.RmiID)3000+7;
			public const Nettention.Proud.RmiID Player_SMove = (Nettention.Proud.RmiID)3000+8;
			public const Nettention.Proud.RmiID RequestAddTree = (Nettention.Proud.RmiID)3000+9;
			public const Nettention.Proud.RmiID RequestRemoveTree = (Nettention.Proud.RmiID)3000+10;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestServerIn,
			RequestLogin,
			RequestRoomList,
			RequestInRoom,
			RequestFastRoom,
			RequestInGame,
			JoinGameScene,
			Player_SMove,
			RequestAddTree,
			RequestRemoveTree,
		};
	}
}
namespace MultiS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReplyServerIn = (Nettention.Proud.RmiID)4000+1;
			public const Nettention.Proud.RmiID ReplyServerFailed = (Nettention.Proud.RmiID)4000+2;
			public const Nettention.Proud.RmiID NotifyLoginSuccess = (Nettention.Proud.RmiID)4000+3;
			public const Nettention.Proud.RmiID NotifyLoginFailed = (Nettention.Proud.RmiID)4000+4;
			public const Nettention.Proud.RmiID ReplyInRoom = (Nettention.Proud.RmiID)4000+5;
			public const Nettention.Proud.RmiID ReplyInGame = (Nettention.Proud.RmiID)4000+6;
			public const Nettention.Proud.RmiID NotifyAddTree = (Nettention.Proud.RmiID)4000+7;
			public const Nettention.Proud.RmiID NotifyRemoveTree = (Nettention.Proud.RmiID)4000+8;
			public const Nettention.Proud.RmiID Player_Appear = (Nettention.Proud.RmiID)4000+9;
			public const Nettention.Proud.RmiID Player_Disappear = (Nettention.Proud.RmiID)4000+10;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReplyServerIn,
			ReplyServerFailed,
			NotifyLoginSuccess,
			NotifyLoginFailed,
			ReplyInRoom,
			ReplyInGame,
			NotifyAddTree,
			NotifyRemoveTree,
			Player_Appear,
			Player_Disappear,
		};
	}
}
namespace MultiC2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ScribblePoint = (Nettention.Proud.RmiID)1000+1;
			public const Nettention.Proud.RmiID OtherCharacterSelect = (Nettention.Proud.RmiID)1000+2;
			public const Nettention.Proud.RmiID Player_CMove = (Nettention.Proud.RmiID)1000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ScribblePoint,
			OtherCharacterSelect,
			Player_CMove,
		};
	}
}

				 
